# Generated by Django 5.2.5 on 2025-09-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('object_type', models.CharField(max_length=64)),
                ('predicted_count', models.IntegerField(default=0)),
                ('corrected_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
