# Generated by Django 5.2.5 on 2025-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('winter', 'winter'), ('dracula', 'dracula'), ('forest', 'forest'), ('dim', 'dim'), ('night', 'night'), ('halloween', 'halloween')], default='winter', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
