apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
